sudo: false
language: cpp
os:
  - linux
env:
  global:
    - SDK_BUILD=258
  matrix:
    - SDK_VERSION=1.5.0  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:     
      - bsdtar
install:
  - git clone https://github.com/patrickjahns/Sming.git
  - cd Sming
  - git checkout rgbwwdev
  - cd ..
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export SDK_FILE_NAME="esp-alt-sdk-v${SDK_VERSION}.${SDK_BUILD}-macos-x86_64.zip"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export SDK_FILE_NAME="esp-alt-sdk-v${SDK_VERSION}.${SDK_BUILD}-linux-x86_64.tar.gz"; fi
  - mkdir -p $TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk
  - wget https://bintray.com/artifact/download/kireevco/generic/${SDK_FILE_NAME}
  - bsdtar -xf ${SDK_FILE_NAME} -C $TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk  
  - rm -rf samples
  - cd $TRAVIS_BUILD_DIR/Sming/Sming/Libraries
  - git clone https://github.com/patrickjahns/RGBWWLed
  - export SMING_HOME=$TRAVIS_BUILD_DIR/Sming/Sming
  - export ESP_HOME=$TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk  
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/Sming/opt/esp-alt-sdk/utils/
  - cd $SMING_HOME
  - make all spiffy/spiffy 
    
script:
  - cd $TRAVIS_BUILD_DIR
  - make all